language: cpp
sudo: required

os:
  -linux
  
dist: sid
 
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  
install:
  - sudo apt-get install -y cmake libboost-dev
  
before_script:
  - git clone https://github.com/Microsoft/GSL.git
  - export GSL_PATH=$PWD/gsl/include

script:
  - mkdir build
  - cd build
  - cmake -DGSL_INCLUDE_DIRS=$GSL_PATH ..
  - make

after_script:
  - ctest .