language: cpp
sudo: required

os:
  -linux
  
dist: trusty
 
compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  
install:
  - sudo apt-get install -y cmake libboost-all-dev libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/Microsoft/GSL.git
  - export GSL_PATH=$PWD/gsl/include

script:
  - mkdir build
  - cd build
  - echo $GSL_PATH
  - ls -l $GSL_PATH
  - ls -l $GSL_PATH/gsl
  - cmake -DGSL_INCLUDE_DIRS:PATH=$GSL_PATH ..
  - make
  - ctest .
